version: "3.8"
services:
  database:
    image: "postgres:14-alpine"
    container_name: vaadin_login_app_db
    ports:
      - "5433:5432"
    environment:
      - 'POSTGRES_DB: vaadin_login_app_db'
      - 'POSTGRES_USER: postgres'
      - 'POSTGRES_PASSWORD: pgadmin'
  redis:
    image: "redis:6.2-alpine"
    container_name: vaadin_login_app_redis
    command: /bin/sh -c "redis-server --requirepass password"
    ports:
      - "6380:6379"